name: Docker Image CI

on:
  push:
    branches: [ "jerry_backend" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4

    - name: Login to DockerHub
      env:
        DOCKER_USERNAME: ${{ secrets.DOCKER_USERNAME }}
        DOCKER_PASSWORD: ${{ secrets.DOCKER_PASSWORD }}
      run: docker login -u $DOCKER_USERNAME -p $DOCKER_PASSWORD

    - name: Build the Docker Image
      run: docker build -t $DOCKER_USERNAME/contract_backend ./backend

    - name: Push to DockerHub
      run: docker push $DOCKER_USERNAME/contract_backend:latest
